### ISSUE TITLE
No break word?

### ISSUE THREAD

**Issue by mzaini30** [Hashnode/user-feedback#187]
![Screenshot_2020-07-23-13-10-17-99](https://user-images.githubusercontent.com/7939342/88253962-37dd0f00-cce6-11ea-807e-c4a9e3625b71.png)

I think, you must write this in your web CSS:

```css
* {
 word-wrap: break-word;
}
```
